#!/usr/bin/env python3
"""Build the public GitHub Pages copy of the dashboard.

This is the ONLY place where private data becomes public, so everything that
crosses that line is visible in one file and can be audited in one read.

What crosses:
  live.json    — public market data (FRED). Nothing personal in it.
  themes.json  — narratives and portfolio impact, after redaction below.

What never crosses:
  profile.local.json — age, employer, account structure, ESPP. The page has
  no use for any of it; only Claude needs it, and only when writing themes.

Holding labels are genericised because a label like "401k EM sleeve (25%)"
leaks an allocation. "AAPL" on its own does not — millions of people hold it.
"""

import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT.parent / "docs" / "macro"

# Applied to portfolio-impact holding labels, longest pattern first.
REDACT = [
    (r"401k EM sleeve \(25%\)", "EM sleeve"),
    (r"401k EM sleeve",          "EM sleeve"),
    (r"\(researching\)",         "(watchlist)"),
    (r"\bESPP\b",                "employer stock"),
    (r"\bHYSA\b",                "Cash"),
]

# Refuse to publish if any of these appear anywhere in the output.
FORBIDDEN = [
    r"Morgan Stanley", r"\bESPP\b", r"\b26\b\s*(?:years|yo)",
    r"Roth\s+401k", r"Roth\s+IRA", r"HYSA", r"\b75%\s*/\s*25%",
]


def redact(themes):
    for theme in themes.get("themes", []):
        for row in theme.get("portfolioImpact", []) or []:
            # Both the label and the reason text can carry account details.
            for field in ("holding", "reason"):
                val = row.get(field, "")
                for pattern, replacement in REDACT:
                    val = re.sub(pattern, replacement, val)
                row[field] = val
    return themes


def audit(text):
    hits = [p for p in FORBIDDEN if re.search(p, text, re.I)]
    return hits


def main():
    live_path   = ROOT / "data" / "live.json"
    themes_path = ROOT / "data" / "themes.json"
    if not live_path.exists():
        print("data/live.json missing — run refresh.py first", file=sys.stderr)
        return 1

    live   = json.loads(live_path.read_text())
    themes = redact(json.loads(themes_path.read_text())) if themes_path.exists() else {}

    payload = json.dumps({"live": live, "themes": themes}, indent=2)

    hits = audit(payload)
    if hits:
        print("REFUSING TO PUBLISH — sensitive patterns found:", file=sys.stderr)
        for h in hits:
            print(f"  {h}", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "data.json").write_text(payload + "\n")

    for name in ("styles.css", "app.js"):
        shutil.copy(ROOT / name, OUT / name)

    # The Pages copy fetches data.json (served over http, so fetch works)
    # rather than loading a generated bundle.js the way the local copy does.
    html = (ROOT / "index.html").read_text()
    html = html.replace(
        '<script src="data/bundle.js"></script>\n<script src="app.js"></script>',
        '<script src="boot.js"></script>')
    html = html.replace("</head>",
        '<link rel="manifest" href="manifest.webmanifest">\n'
        '<meta name="theme-color" content="#0a0a0f">\n'
        '<meta name="apple-mobile-web-app-capable" content="yes">\n'
        '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n'
        '<link rel="apple-touch-icon" href="icon-180.png">\n'
        "</head>")
    (OUT / "index.html").write_text(html)

    # Fetch the data, then run the renderer. Cache-busted so a phone that has
    # the page installed still sees today's numbers rather than yesterday's.
    (OUT / "boot.js").write_text("""// Generated by scripts/build_public.py
(async () => {
  try {
    const r = await fetch('data.json?t=' + Date.now(), { cache: 'no-store' });
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const d = await r.json();
    window.__LIVE__ = d.live;
    window.__THEMES__ = d.themes;
  } catch (e) {
    // Offline or fetch failed — fall back to whatever the service worker cached.
    console.warn('Live fetch failed, using cache:', e.message);
    try {
      const c = await caches.match('data.json');
      if (c) { const d = await c.json(); window.__LIVE__ = d.live; window.__THEMES__ = d.themes; }
    } catch (_) {}
    window.__STALE__ = true;
  }
  const s = document.createElement('script');
  s.src = 'app.js';
  document.body.appendChild(s);
})();
""")

    # Register the service worker so the page installs to a phone home screen.
    boot = (OUT / "boot.js").read_text()
    boot += ("\nif ('serviceWorker' in navigator) {\n"
             "  window.addEventListener('load', () =>\n"
             "    navigator.serviceWorker.register('sw.js').catch(() => {}));\n}\n")
    (OUT / "boot.js").write_text(boot)

    (OUT / "manifest.webmanifest").write_text(json.dumps({
        "name": "Macro Tracker",
        "short_name": "Macro",
        "start_url": ".",
        "display": "standalone",
        "background_color": "#0a0a0f",
        "theme_color": "#0a0a0f",
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png"},
        ],
    }, indent=2) + "\n")

    # Network-first for data so a refresh always tries live before cache;
    # cache-first for the shell so it opens instantly and works offline.
    (OUT / "sw.js").write_text("""const SHELL = 'macro-shell-v1';
const FILES = ['./', 'index.html', 'styles.css', 'app.js', 'boot.js',
               'manifest.webmanifest'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(SHELL).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== SHELL).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  if (url.pathname.endsWith('data.json')) {
    e.respondWith(fetch(e.request)
      .then(r => { const copy = r.clone();
        caches.open(SHELL).then(c => c.put('data.json', copy)); return r; })
      .catch(() => caches.match('data.json')));
    return;
  }
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request)));
});
""")

    print(f"Built {OUT}")
    print(f"  data.json  {len(payload)} bytes")
    print(f"  audit      clean — no sensitive patterns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
