#!/usr/bin/env python3
"""Refresh the quantitative half of the dashboard.

Only touches NUMBERS — index levels, rates, CPI/PPI. The qualitative half
(what changed, portfolio impact, catalysts) lives in data/themes.json and is
written by a person or by Claude, because judgment is not something a cron
job can produce.

Everything comes from FRED's fredgraph.csv endpoint, which needs no API key
and no account. (Note: FRED's *documented* API at api.stlouisfed.org does
require a key — it returns 400 without one. This CSV endpoint does not.)

That means zero secrets, nothing to rotate, nothing to leak. The tradeoff is
that FRED publishes daily closes rather than intraday quotes, so index levels
are last close, occasionally one session behind. For a dashboard you open in
the morning, that is the correct number anyway.
"""

import csv
import io
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / "data" / "live.json"
URL  = "https://fred.stlouisfed.org/graph/fredgraph.csv?id={sid}"

# id -> (label, unit, mode)
#   level = latest observation, with change vs the prior observation
#   yoy   = percent change against the observation 12 periods back
MARKET = {
    "SP500":     ("S&P 500", "",  "level"),
    "NASDAQCOM": ("Nasdaq",  "",  "level"),
    "VIXCLS":    ("VIX",     "",  "level"),
}
MACRO = {
    "DFF":      ("Fed funds rate",   "%", "level"),
    "DGS10":    ("10-year Treasury", "%", "level"),
    "CPIAUCSL": ("CPI",              "%", "yoy"),
    "PPIACO":   ("PPI",              "%", "yoy"),
}


def series(series_id):
    """Return [(date, value)] oldest-first. FRED writes '.' for gaps."""
    r = httpx.get(URL.format(sid=series_id), timeout=30, follow_redirects=True)
    r.raise_for_status()

    rows = []
    for row in csv.reader(io.StringIO(r.text)):
        if len(row) < 2 or not row[0][:1].isdigit():
            continue
        try:
            rows.append((row[0], float(row[1])))
        except ValueError:
            continue
    return rows


def build(series_id, label, unit, mode):
    rows = series(series_id)
    if not rows:
        raise ValueError("no observations")

    if mode == "yoy":
        # An index level like CPI 332.568 means nothing to a reader. The rate
        # of change is the story, so convert before it reaches the dashboard.
        if len(rows) < 13:
            raise ValueError("insufficient history for year-over-year")
        latest, prior = rows[-1][1], rows[-13][1]
        if not prior:
            raise ValueError("zero base")
        return {
            "label": label,
            "value": round((latest - prior) / prior * 100, 2),
            "unit": "%", "note": "year over year",
            "changePct": None,
        }, rows[-1][0]

    latest = rows[-1][1]
    change = None
    if len(rows) >= 2 and rows[-2][1]:
        change = round((latest - rows[-2][1]) / rows[-2][1] * 100, 2)
    return {
        "label": label,
        "value": round(latest, 2),
        "unit": unit, "note": "last close",
        "changePct": change,
    }, rows[-1][0]


def collect(spec, heading):
    print(heading)
    out, errors = {}, []
    for sid, (label, unit, mode) in spec.items():
        try:
            entry, as_of = build(sid, label, unit, mode)
            entry.update({
                "asOf": as_of,
                "source": f"FRED {sid}",
                "sourceUrl": f"https://fred.stlouisfed.org/series/{sid}",
            })
            out[sid] = entry
            chg = "" if entry["changePct"] is None else f"  ({entry['changePct']:+}%)"
            print(f"  {sid:<10} {entry['value']}{entry['unit']}{chg}  [{as_of}]")
        except Exception as e:
            errors.append(f"{sid}: {e}")
            print(f"  {sid:<10} FAILED — {e}")
    return out, errors


def write_bundle():
    """Emit data/bundle.js so index.html works from file:// directly.

    Browsers block fetch() against file:// for security, which would make a
    double-clickable page unable to read its own JSON. A script tag has no
    such restriction, so the same data is also written as a JS assignment.
    JSON stays the source of truth; this is a generated view of it.
    """
    live   = json.loads((ROOT / "data" / "live.json").read_text())
    themes_path = ROOT / "data" / "themes.json"
    themes = json.loads(themes_path.read_text()) if themes_path.exists() else {}

    bundle = ROOT / "data" / "bundle.js"
    bundle.write_text(
        "// Generated by scripts/refresh.py — do not edit.\n"
        f"window.__LIVE__ = {json.dumps(live, indent=2)};\n"
        f"window.__THEMES__ = {json.dumps(themes, indent=2)};\n"
    )
    print(f"Wrote {bundle}")


def main():
    bundle_only = "--bundle-only" in sys.argv

    if not bundle_only:
        market, market_errors = collect(MARKET, "Market snapshot (FRED)...")
        macro,  macro_errors  = collect(MACRO,  "Macro series (FRED)...")

        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(json.dumps({
            "updated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "market": market,
            "macro": macro,
            "errors": market_errors + macro_errors,
        }, indent=2) + "\n")
        print(f"\nWrote {OUT}")
    else:
        market = macro = {"skipped": True}

    write_bundle()

    if not market and not macro:
        print("ERROR: no data retrieved", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
